image: python:3.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -e .
  - pip install -e .["linters"]

test:
  script:
    - pylint *
    - mypy src/monmon/
    - black --check .

run:
  script:
    - python main.py
